Title = "SaraSortd Config"

[Variables] # Only use these in config files, not the actual file names themselves..
NextNum = "*" # The next available number. If 1 already exists, 2 will be used. Starts at 1.
NextChar = "&" # The next available character. If A already exists, B will be used.

Parent = "@" # The name of the parent directory.

OrgFileName = "~" # The original name of the sorted file. If "blahblah.txt" gets sorted, "~" would be equal to "blahblah".
OrgFileType = "^" # The original file type of the sorted file. If "example.png" gets sorted, "^" would be equal to ".png".

Year = "[y]" # The current year, E.G. "2026".

MonthName = "[M]" # The name of the current month, E.G. "March".
DayName = "[D]" # The name of the current day, E.G. "Friday".

Month = "[m]" # The date of the current month, E.G. "03".
Day = "[d]" # The date of the current day, E.G. "27".

Hour = "[h]" # The current hour, E.G. "12".
Minute = "[n]" # The current minute, E.G. "44".
Second = "[s]" # The current second, E.G. "11".

VarCall  = "%%" # The characters used at the start and end of variable calls. The first character is to the left; second is to the right.

[DirectoryPaths]
RootDir = "Unset"
InputDir = "%RootDir%"
OutputDir = "%RootDir%"
LogDir = ".%RootDir%/Logs"
FailedDir =".%RootDir%/Failed" # For files that failed to be sorted.

[Names]
OutputFileName = "*_@^" # Name of sorted files.
LogFileName = "[y].[m].[d]_*" # Name of log files.
ConfFileName = ".@Config" # Name of config files for directories.

[Log]
Sorted = "Sorted ~^ to %SortDir%"