Title = "Unset"
LastFile = "Unset"
ParentDir = "Unset"

[[Files]]
Pattern = "*.jpg"
NewFileName = "~^"
NextNum = 1
NextChar = "A"
CaseSensitive = 0

[[Files]]
Pattern = "*.png"
NewFileName = "~^"
NextNum = 1
NextChar = "A"
CaseSensitive = 0